### ISSUE TITLE
Code error for Analysis of Synaptic events fitting with user data

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#210]
### Expected behavior

Analysis shows table

### Actual Behavior

Error message:

```
AttributeErrorTraceback (most recent call last)
<ipython-input-6-f3fffc1de11c> in tabledata(_)
    218         tograph=1
    219     if tograph==1:
--> 220         datasorted = data.sort([NAMES[2]], ascending=1)
    221         display(HTML(datasorted.to_html(index=False)))
    222 

/opt/conda/envs/python2/lib/python2.7/site-packages/pandas/core/generic.pyc in __getattr__(self, name)
   3612             if name in self.

_info_axis:
   3613                 return self[name]
-> 3614             return object.__getattribute__(self, name)
   3615 
   3616     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'sort'
```
![screen shot 2018-02-28 at 12 43 12](https://user-images.githubusercontent.com/12729291/36785963-f95e668e-1c84-11e8-919f-9de4c9e05ec1.png)
### Steps to reproduce the problem

 - Run the fit with the demo version
 - Insert the values 82, -60, 0
 - Select the results from storage (after NSG job finished)
 - Select "Results table"

**Comment by clupascu** [comment]
Can you add me to the test collab please? Thanks.

**Comment by alex4200** [comment]
done

**Comment by clupascu** [comment]
I can't reproduce this one. Can you try it again?

**Comment by alex4200** [comment]
@clupascu : I got the same error again: 

![selection_251](https://user-images.githubusercontent.com/12729291/36840676-298b7f10-1d46-11e8-88fe-be088dd3de8c.png)


I added you to that Collab (Dev2).

**Comment by alex4200** [comment]
When I click on 'Boxplot results' instead I get the following error:

```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

INFO:root:
Unfortunately, your original traceback can not be constructed.

Traceback (most recent call last):
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/conda/envs/python2/lib/python2.7/inspect.py", line 1051, in getinnerframes
    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))
  File "/opt/conda/envs/python2/lib/python2.7/inspect.py", line 1011, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/opt/conda/envs/python2/lib/python2.7/inspect.py", line 453, in getsourcefile
    if hasattr(getmodule(object, filename), '__loader__'):
  File "/opt/conda/envs/python2/lib/python2.7/inspect.py", line 482, in getmodule
    file = getabsfile(object, _filename)
  File "/opt/conda/envs/python2/lib/python2.7/inspect.py", line 466, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/opt/conda/envs/python2/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory


IndexErrorTraceback (most recent call last)
/opt/conda/envs/python2/lib/python2.7/site-packages/ipywidgets/widgets/widget_button.pyc in _handle_button_msg(self, _, content, buffers)
     70         """
     71         if content.get('event', '') == 'click':
---> 72             self._click_handlers(self)

/opt/conda/envs/python2/lib/python2.7/site-packages/ipywidgets/widgets/widget.pyc in __call__(self, *args, **kwargs)
     66                     self.log.warn("Exception in callback %s: %s", callback, e, exc_info=True)
     67                 else:
---> 68                     ip.showtraceback()
     69             else:
     70                 value = local_value if local_value is not None else value

/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in showtraceback(self, exc_tuple, filename, tb_offset, exception_only)
   1824                     except Exception:
   1825                         stb = self.InteractiveTB.structured_traceback(etype,
-> 1826                                             value, tb, tb_offset=tb_offset)
   1827 
   1828                     self._showtraceback(etype, value, stb)

/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1409         self.tb = tb
   1410         return FormattedTB.structured_traceback(
-> 1411             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1412 
   1413 

/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1317             # Verbose modes need a full traceback
   1318             return VerboseTB.structured_traceback(
-> 1319                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1320             )
   1321         else:

/opt/conda/envs/python2/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1202                 structured_traceback_parts += formatted_exception
   1203         else:
-> 1204             structured_traceback_parts += formatted_exception[0]
   1205 
   1206         return structured_traceback_parts

IndexError: string index out of range
```

**Comment by clupascu** [comment]
I don't get the 'DataFrame' object has no attribute 'sort' error. I tested into the Collab (Dev2).
![schermata 2018-03-01 alle 21 57 06](https://user-images.githubusercontent.com/22050958/36869349-c9723028-1d9b-11e8-830e-71fae24441c7.png)

**Comment by clupascu** [comment]
I don't get any error when I click on 'Boxplot results'.
![schermata 2018-03-01 alle 22 00 34](https://user-images.githubusercontent.com/22050958/36869433-15e65bb4-1d9c-11e8-80bb-b407ccdb381e.png)

**Comment by alex4200** [comment]
@clupascu : I am confused regarding the `DataFrame` error. I gave pandas version 0.22.0 installed, and according to the documentation here

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

a `DataFrame` does not contain a method `sort`. Maybe you are using a different version of pandas? if so, I suggest to make sure at the begin of the notebook that a compatible version is installed automatically.

I just confirmed that with another user and pandas 0.19.2 this plot works fine. So I guess you have to add some code to check the version and to downgrade if neccessary...

The 'Boxplot' result is working as well as the 'Best Fit'.

**Comment by clupascu** [comment]
I fixed this too. Can you please check again? Thanks.

**Comment by alex4200** [comment]
Code has been added to check the version compability. Works now...
