### ISSUE TITLE
Unable to load the app in firefox

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#293]
The page at 

https://bsp-mouse-o1.humanbrainproject.eu/

does not load in firefox:

![screen shot 2018-05-17 at 11 06 09](https://user-images.githubusercontent.com/12729291/40167860-62e48a50-59c2-11e8-943d-b34479867b96.png)

**Comment by pgetta** [comment]
From logs:

```
[D 180517 09:33:34 sim:55] creating simulation
[D 180517 09:33:34 sim:66] creating bglibpy SSim instance
[D 180517 09:33:35 sim:69] instantiating ssim gids: [12607, 18986]
[D 180517 09:33:43 sim:99] adding recording section for L4_cADpyr_486239338_bglibpy[0].soma[0] in cell 21186
Process Process-28:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/blue_pair/sim.py", line 46, in get_sim_traces_mp
    sim = Sim(sim_config, progress)
  File "/usr/local/lib/python2.7/site-packages/blue_pair/sim.py", line 73, in __init__
    self._add_recording_section(recording)
  File "/usr/local/lib/python2.7/site-packages/blue_pair/sim.py", line 102, in _add_recording_section
    self.ssim.cells[gid].add_voltage_recording(sec, .5)
KeyError: 21186
```

**Comment by pgetta** [comment]
Okey, it was an issue with backend, somehow relevant to https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/298, fixed now.

**Comment by alex4200** [comment]
Working now in firefox...

**Comment by alex4200** [comment]
Correcting statement: Its working in Firefox on Linux, but NOT in Firefox on MacOS!

**Comment by alex4200** [comment]
Yes working now in Firefox in MacOS.
