### ISSUE TITLE
Basal Ganglia notebook: error in penultimate line (opt.run(max_ngen=10,....)) [Johannes]

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#37]
### Actual Behavior
Error raised:
```

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-11-0e1268f6f9e1> in <module>()
      2                 offspring_size=10,
      3                 continue_cp=False,
----> 4                 cp_filename='save/FS-notebook-run.pickle')

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/deapext/optimisations.pyc in run(self, max_ngen, offspring_size, continue_cp, cp_filename, cp_frequency)
    288             cp_frequency=cp_frequency,
    289             continue_cp=continue_cp,
--> 290             cp_filename=cp_filename)
    291 
    292         return pop, self.hof, log, history

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/deapext/algorithms.pyc in eaAlphaMuPlusLambdaCheckpoint(population, toolbox, mu, cxpb, mutpb, ngen, stats, halloffame, cp_frequency, cp_filename, continue_cp)
    117 
    118         # TODO this first loop should be not be repeated !
--> 119         invalid_count = _evaluate_invalid_fitness(toolbox, population)
    120         _update_history_and_hof(halloffame, history, population)
    121         _record_stats(stats, logbook, start_gen, population, invalid_count)

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/deapext/algorithms.pyc in _evaluate_invalid_fitness(toolbox, population)
     39     '''
     40     invalid_ind = [ind for ind in population if not ind.fitness.valid]
---> 41     fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
     42     for ind, fit in zip(invalid_ind, fitnesses):
     43         ind.fitness.values = fit

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/evaluators.pyc in evaluate_with_lists(self, param_list)
    185         param_dict = self.param_dict(param_list)
    186 
--> 187         obj_dict = self.evaluate_with_dicts(param_dict=param_dict)
    188 
    189         return self.objective_list(obj_dict)

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/evaluators.pyc in evaluate_with_dicts(self, param_dict)
    176         responses = self.run_protocols(
    177             self.fitness_protocols.values(),
--> 178             param_dict)
    179 
    180         return self.fitness_calculator.calculate_scores(responses)

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/evaluators.pyc in run_protocols(self, protocols, param_values)
    161                 protocol,
    162                 param_values=param_values,
--> 163                 isolate=self.isolate_protocols))
    164 
    165         return responses

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/evaluators.pyc in run_protocol(self, protocol, param_values, isolate, cell_model, sim)
    150             param_values,
    151             sim=sim,
--> 152             isolate=isolate)
    153 
    154     def run_protocols(self, protocols, param_values):

/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/protocols.pyc in run(self, cell_model, param_values, sim, isolate)
    183                     'cell_model': cell_model,
    184                     'param_values': param_values,
--> 185                     'sim': sim})
    186 
    187             pool.terminate()

/usr/lib/python2.7/multiprocessing/pool.pyc in apply(self, func, args, kwds)
    242         '''
    243         assert self._state == RUN
--> 244         return self.apply_async(func, args, kwds).get()
    245 
    246     def map(self, func, iterable, chunksize=None):

/usr/lib/python2.7/multiprocessing/pool.pyc in get(self, timeout)
    556             return self._value
    557         else:
--> 558             raise self._value
    559 
    560     def _set(self, i, obj):

Exception: Traceback (most recent call last):
  File "/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/protocols.py", line 130, in _run_func
    cell_model.instantiate(sim=sim)
  File "/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/models.py", line 225, in instantiate
    mechanism.instantiate(sim=sim, icell=self.icell)
  File "/home/jupyter/.local/lib/python2.7/site-packages/bluepyopt/ephys/mechanisms.py", line 105, in instantiate
    raise ValueError(str(e) + ': ' + self.suffix)
ValueError: argument not a density mechanism name.: naffs
```

### Steps to reproduce the problem
Run the notebook

**Comment by Hjorthmedh** [comment]
This error does not materialise for me. Basically it comes down to nrnivmodl not being run to compile the modules needed by neuron, which is strange. How persistent is the environment between different notebooks for different users vs for the same user?

**Comment by alex4200** [comment]
@Hjorthmedh: I just retested this notebook, and I see the same error.

**Comment by alex4200** [comment]
@Hjorthmedh: New notebook seems to work, runs all the way through. Closing this ticket!
