### ISSUE TITLE
BUG: optimization jobs end with error on NSG

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#492]
### Expected behavior
The optimization jobs submitted to NSG ends successfully

### Actual Behavior (please include screenshot if possible)
The optimization jobs submitted to NSG give the following error: 

Traceback (most recent call last):
  File "opt_neuron.py", line 68, in <module>
    import model
  File "/projects/ps-nsg/home/nsguser/ngbwr/workspace/NGBW-JOB-BLUEPYOPT_TG-E99B9052BBA643DCA4D1AB2F8268758A/CA1_int_bAC_011017HP2_20180110153901/model/__init__.py", line 19, in <module>
    import analysis
**ModuleNotFoundError: No module named 'analysis'**

### Steps to reproduce the problem
Launch an optimization job via either the:
  - "HH-Neuron-Builder" use case
  - "Rebuild an existing single hippocampal cell model" use case
  - "Build your own single hippocampal cell model using HBP data" use case

**Comment by lbologna** [comment]
After email exchange with NSG and a system status reversion, the issue has been solved.
Note: NSG will pass to python3 as the default python interpreter in the first weeks of December.
Closing the issue.
