### ISSUE TITLE
Error for "Rebuild Cell" for PizDaint and Service Account 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#500]
### Expected behavior

Simulation runs successfully and downloads a output.tar.gz file to the Collab's storage

### Actual Behavior (please include screenshot if possible)

When running with PizDaint or the Service Account no output.tar.gz file is created in the Collab storage. The stderr file contains the following error:

```
Traceback (most recent call last):
  File "/users/bp000178/ich002/software/daint/local-20181022101238/pyenv/bin/ipengine", line 7, in <module>
    from ipyparallel.apps.ipengineapp import launch_new_instance
  File "/users/bp000178/ich002/software/daint/local-20181022101238/pyenv/lib/python2.7/site-packages/ipyparallel/__init__.py", line 11, in <module>
    import zmq
  File "/users/bp000178/ich002/software/daint/local-20181022101238/pyenv/lib/python2.7/site-packages/zmq/__init__.py", line 42, in <module>
    _load_libzmq()
  File "/users/bp000178/ich002/software/daint/local-20181022101238/pyenv/lib/python2.7/site-packages/zmq/__init__.py", line 9, in _load_libzmq
    import sys, ctypes, platform, os
ImportError: No module named ctypes
```

and the following error:

```
+ python opt_neuron.py --offspring_size=10 --max_ngen=2 --start --checkpoint checkpoints/checkpoint.pkl
Traceback (most recent call last):
  File "opt_neuron.py", line 31, in <module>
    import argparse
  File "/users/bp000178/ich002/software/daint/local-20181022101238/pyenv/lib/python2.7/site-packages/argparse.py", line 91, in <module>
    import copy as _copy
ImportError: No module named copy
```

### Steps to reproduce the problem

1. Clone the use case "Rebuild Single HippoCell " with the first model
2. Run all cells.
3. Start a simulation on PizDaint / Service Account with no parameters changed
4. Wait until the job is successful
5. Check the Storage

### Optional infrastructural data (user, platform, browser, environment, ...)

Notebook is still with python2 kernel. 

[stderr.zip](https://github.com/cnr-ibf-pa/hbp-bsp-issues/files/4029596/stderr.zip)

see also: https://bbpteam.epfl.ch/project/issues/browse/BBPP42-534

**Same BUG as described in #491 . I will leave both tickets open as they refer to different applications and needs to be tested independently.**

**Comment by clupascu** [comment]
See #491. Once it is tested we can close this ticket too.

**Comment by alex4200** [comment]
Obsolete ticket as usecases will be changed for python 3 support, see #520 .
